### ISSUE TITLE
[CS 591 CAS] Fall 2019 Week 5 Presentation

### ISSUE THREAD

**Issue by MacProSector** [ashishkashinath/asrg_papers#2]
My name is Simon Yu, one of the students in Fall 2019 CS 591 CAS who volunteered to present in week 5.

For this week's seminar, I would like to present the following three papers:

1. "uavEE: A Modular, Power-Aware Emulation Environment for Rapid Prototyping and Testing of UAVs" <https://ieeexplore.ieee.org/document/8607252>
2. "Flight Testing Automation to Parameterize Unmanned Aircraft Dynamics" <https://arc.aiaa.org/doi/abs/10.2514/6.2019-3230>
3. "Trajectory Estimation for Geo-Fencing Applications on Small-Size Fixed-Wing UAVs" <IROS 2019>

I plan to present paper 1 first on a modular UAV emulation environment and then present paper 2 and 3 on some extensions and practical applications using the emulation environment. I could not provide the link to paper 3 yet since it has only been accepted to IROS 2019 recently which is taking place in November this year. I am still in the process of curating slides for the presentation, and I will make it available after the presentation on Wednesday.

**Comment by ashishkashinath** [comment]
Closing
