### ISSUE TITLE
Presentation Proposal for 11/20

### ISSUE THREAD

**Issue by ayoosh** [ashishkashinath/asrg_papers#4]
Presenter: Ayoosh Bansal
Advisors: Lui Sha, Marco Caccamo
Date: Nov 20, 2019
Time: 4:00 PM
Location: Siebel 3405
Course Number: CS591CAS
CNR: 53935
----------------------------------------------------------
Paper: Edge Computing for Autonomous Driving: Opportunities and Challenges
Link to paper: https://ieeexplore.ieee.org/abstract/document/8744265
Abstract:
Safety is the most important requirement for autonomous vehicles; hence, the ultimate challenge of designing an edge computing ecosystem for autonomous vehicles is to deliver enough computing power, redundancy, and security so as to guarantee the safety of autonomous vehicles. Specifically, autonomous driving systems are extremely complex; they tightly integrate many technologies, including sensing, localization, perception, decision making, as well as the smooth interactions with cloud platforms for high-definition (HD) map generation and data storage. These complexities impose numerous challenges for the design of autonomous driving edge computing systems. First, edge computing systems for autonomous driving need to process an enormous amount of data in real time, and often the incoming data from different sensors are highly heterogeneous. Since autonomous driving edge computing systems are mobile, they often have very strict energy consumption restrictions. Thus, it is imperative to deliver sufficient computing power with reasonable energy consumption, to guarantee the safety of autonomous vehicles, even at high speed. Second, in addition to the edge system design, vehicle-to-everything (V2X) provides redundancy for autonomous driving workloads and alleviates stringent performance and energy constraints on the edge side. With V2X, more research is required to define how vehicles cooperate with each other and the infrastructure. Last, safety cannot be guaranteed when security is compromised. Thus, protecting autonomous driving edge computing systems against attacks at different layers of the sensing and computing stack is of paramount concern. In this paper, we review state-of-the-art approaches in these areas as well as explore potential solutions to address these challenges.
----------------------------------------------------------

**Comment by ashishkashinath** [comment]
Closing, as prescribed.
